export interface SelectedElectionDetailsCard{
    title:string;
    to?:string;
    icon:string;
    leftValue:number;
    leftLable:string;
    rightValue:number;
    rightLable:string;
}

export interface Election {
    id: number;
    organization_id: number;
    user_id: number;
    name: string;
    description: string;
    logo: string;
    status: string;
    stage: string;
    start: Date;
    end: Date;
    created_at: Date;
    updated_at: Date;
    voters_count: number;
    stages: Stage[];
    created_by: CreatedBy;
}

export interface CreatedBy {
    id: number;
    selected_organization_id: number;
    first_name: string;
    last_name: string;
    email: string;
    avatar: string;
    current_organization: CurrentOrganization;
}

export interface CurrentOrganization {
    id: number;
    user_id: number;
    name: string;
    description: string;
    logo: string;
    created_at: Date;
    updated_at: Date;
}

export interface Stage {
    id: number;
    election_id: number;
    stage: string;
    start: Date;
    end: Date;
}
// Generated by https://quicktype.io

export interface Stats {
    voters: Voters;
    nominations: Nominations;
    pollingStations: Campaigns;
    campaigns: Campaigns;
}

export interface Campaigns {
    total: number;
    active: number;
}

export interface Nominations {
    submitted: number;
    approved: number;
}

export interface Voters {
    total: number;
    voted: number;
}
